# Generated by Django 5.2.14 on 2026-05-13 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('total_requests', models.IntegerField()),
                ('error_requests', models.IntegerField()),
                ('avg_response_time', models.FloatField()),
            ],
            options={
                'db_table': 'system_metrics',
            },
        ),
    ]
