# Generated by Django 6.0.4 on 2026-05-09 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_warehouse'),
    ]

    operations = [
        migrations.RunSQL(
            """
            CREATE TRIGGER product_before_insert
            BEFORE INSERT ON products_product
            FOR EACH ROW
            BEGIN
                IF NEW.price < 0 THEN
                    SIGNAL SQLSTATE '45000'
                    SET MESSAGE_TEXT = 'Цена не может быть отрицательной';
                END IF;

                IF NEW.quantity_in_stock < 0 THEN
                    SIGNAL SQLSTATE '45000'
                    SET MESSAGE_TEXT = 'Количество не может быть отрицательным';
                END IF;

                IF NEW.name IS NULL OR NEW.name = '' THEN
                    SIGNAL SQLSTATE '45000'
                    SET MESSAGE_TEXT = 'Название обязательно';
                END IF;
            END;
            """,
            reverse_sql="DROP TRIGGER IF EXISTS product_before_insert;",
        ),

        migrations.RunSQL(
            """
            CREATE TRIGGER product_before_update
            BEFORE UPDATE ON products_product
            FOR EACH ROW
            BEGIN
                IF NEW.price < 0 THEN
                    SIGNAL SQLSTATE '45000'
                    SET MESSAGE_TEXT = 'Цена не может быть отрицательной';
                END IF;

                IF NEW.quantity_in_stock < 0 THEN
                    SIGNAL SQLSTATE '45000'
                    SET MESSAGE_TEXT = 'Количество не может быть отрицательным';
                END IF;

                IF NEW.name IS NULL OR NEW.name = '' THEN
                    SIGNAL SQLSTATE '45000'
                    SET MESSAGE_TEXT = 'Название обязательно';
                END IF;
            END;
            """,
            reverse_sql="DROP TRIGGER IF EXISTS product_before_update;",
        ),
    ]
