# Generated by Django 6.0.4 on 2026-05-01 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='final_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('Card', 'Оплата картой'), ('PayPal', 'PayPal'), ('Cash', 'Наличные'), ('SBP', 'СБП')], db_index=True, max_length=20)),
                ('transaction_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('paid_amount', models.DecimalField(decimal_places=2, editable=False, max_digits=12, null=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='sales.order')),
            ],
            options={
                'db_table': 'transactions',
            },
        ),
    ]
